import assert from 'node:assert/strict';
import { test, after } from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { createSessionCookie } from '../functions/_lib/nuvio-session.js';
import { onRequestGet as get, onRequestPost as post } from '../functions/api/forum.js';
import { forumDb } from '../functions/_lib/forum.js';
const realFetch=globalThis.fetch;
globalThis.fetch=async()=>Response.json([{profile_index:1,name:'First profile'},{profile_index:2,name:'Second profile'}]);
after(()=>{globalThis.fetch=realFetch;});
function database(){const sqlite=new DatabaseSync(':memory:');return {prepare(sql){const build=args=>({bind:(...values)=>build(values),async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};},async first(){return sqlite.prepare(sql).get(...args);},async all(){return {results:sqlite.prepare(sql).all(...args)};}});return build([]);},async batch(items){return Promise.all(items.map(s=>s.run()));}};}
function fixture(){const env={DB:database(),KOLLECTION_SESSION_SECRET:'forum-test-secret',NUVIO_ADMIN_USER_ID:'admin'};return {env,async call(user,data,params={},origin='https://kollection.tv'){const headers={'Content-Type':'application/json',Origin:origin};if(user)headers.Cookie=(await createSessionCookie({user:{id:user,email:user+'@private.test'},accessToken:'private-token',expiresIn:3600},env)).split(';')[0];const ctx={env,request:new Request('https://kollection.tv/api/forum?'+new URLSearchParams(params),{headers,method:data?'POST':'GET',...(data?{body:JSON.stringify({profileId:1,...data})}:{})})};const r=await(data?post:get)(ctx);return {status:r.status,data:await r.json()};}};}
const topic={action:'topic',categoryId:1,title:'A new discussion',body:'A message for the community.'};
test('one account identity, current avatar/name, counts and private data protection',async()=>{
 const f=fixture();assert.equal((await f.call(null,topic)).status,401);assert.equal((await f.call('alice',topic,{},'https://evil.test')).status,403);
 const created=await f.call('alice',{...topic,author:'Impersonator',user_id:'admin'});assert.equal(created.status,201);const id=created.data.id;
 const detail=await f.call(null,null,{view:'topic',id});assert.equal(detail.data.topic.author,'First profile');assert.doesNotMatch(JSON.stringify(detail),/private.test|private-token|user_id|Impersonator/);
 const member=detail.data.topic.member_id;assert.equal((await f.call('alice',{action:'reply',id,body:'Another reply',profileId:2})).status,201);
 assert.equal((await f.call('alice',{action:'profile',about:'About me text',profileId:2})).data.memberId,member);
 let profile=await f.call(null,null,{view:'member',id:member});assert.equal(profile.data.member.topic_count,1);assert.equal(profile.data.member.reply_count,1);assert.equal(profile.data.member.about,'About me text');
 const db=await forumDb(f.env);await db.prepare("INSERT INTO account_preferences(user_id,display_name,updated_at) VALUES('alice','Account name','now')").run();await db.prepare("INSERT INTO account_avatars(user_id,id,url,image,updated_at) VALUES('alice','avatar-id','https://example.com/a.jpg','','now')").run();
 profile=await f.call(null,null,{view:'member',id:member});assert.equal(profile.data.member.author,'Account name');assert.equal(profile.data.member.avatar_url,'https://example.com/a.jpg');assert.equal((await f.call('bob',null,{view:'self'})).data.myMemberId,null);
});
test('category management, admin permissions, locking, hiding, restoration and counts',async()=>{
 const f=fixture();assert.equal((await f.call('member',null,{view:'admin'})).status,403);assert.equal((await f.call(null,null,{moderation:1})).status,403);
 const cat={action:'category',name:'Custom',description:'Custom category',position:5,archived:false,readOnly:false};assert.equal((await f.call('member',cat)).status,403);assert.equal((await f.call('admin',cat)).status,200);assert.equal((await f.call('admin',cat)).status,400);
 const c=(await f.call('admin',null,{view:'admin'})).data.categories.find(x=>x.name==='Custom');assert.equal((await f.call('alice',{...topic,categoryId:4})).status,403);
 const id=(await f.call('alice',{...topic,categoryId:c.id})).data.id;const mod={action:'topicModerate',id,categoryId:1,pinned:true,locked:true,hidden:false};assert.equal((await f.call('alice',mod)).status,403);assert.equal((await f.call('admin',mod)).status,200);
 assert.equal((await f.call('bob',{action:'reply',id,body:'Reply'})).status,409);assert.equal((await f.call('admin',{action:'reply',id,body:'Admin reply'})).status,201);
 let d=(await f.call('admin',null,{view:'topic',id})).data;const replyId=d.replies[0].id;assert.equal((await f.call('bob',{action:'replyModerate',id:replyId,hidden:true})).status,403);
 await f.call('admin',{action:'replyModerate',id:replyId,hidden:true});d=(await f.call(null,null,{view:'topic',id})).data;assert.equal(d.replies.length,0);assert.equal(d.topic.reply_count,0);
 await f.call('admin',{...mod,hidden:true});assert.equal((await f.call(null,null,{view:'topic',id})).status,404);assert.equal((await f.call(null)).data.topics.length,0);assert.equal((await f.call('admin',null,{moderation:1})).data.topics.length,1);assert.equal((await f.call(null,null,{view:'member',id:d.topic.member_id})).data.member.topic_count,0);
 await f.call('admin',{...mod,hidden:false,locked:false});assert.equal((await f.call(null,null,{view:'topic',id})).status,200);await f.call('admin',{action:'replyModerate',id:replyId,hidden:false});assert.equal((await f.call(null,null,{view:'topic',id})).data.topic.reply_count,1);
 assert.equal((await f.call('admin',{...cat,id:c.id,name:'Renamed',archived:true})).status,200);assert.equal((await f.call('alice',{...topic,categoryId:c.id})).status,400);
});
test('member restrictions and forum-wide read-only mode are enforced',async()=>{
 const f=fixture(),id=(await f.call('alice',topic)).data.id,m=(await f.call('alice',null,{view:'self'})).data.myMemberId;const ban={action:'memberModerate',id:m,banned:true,clearAbout:true};assert.equal((await f.call('alice',ban)).status,403);await f.call('admin',ban);
 for(const data of [topic,{action:'reply',id,body:'Blocked'},{action:'profile',about:'Blocked'}])assert.equal((await f.call('alice',data)).status,403);
 await f.call('admin',{...ban,banned:false});assert.equal((await f.call('alice',{action:'reply',id,body:'Allowed'})).status,201);
 await f.call('admin',{action:'settings',postingOpen:false});assert.equal((await f.call('alice',topic)).status,409);assert.equal((await f.call('bob',{action:'reply',id,body:'Blocked'})).status,409);assert.equal((await f.call('admin',topic)).status,201);
 const own=(await f.call('admin',null,{view:'self'})).data.myMemberId;assert.equal((await f.call('admin',{...ban,id:own})).status,400);
});
test('quotas, pagination, validation and literal searches',async()=>{
 const f=fixture();for(const bad of [{...topic,title:''},{...topic,body:'x'.repeat(10001)},{action:'profile',about:'x'.repeat(1001)},{action:'unknown'}])assert.equal((await f.call('alice',bad)).status,400);
 assert.equal((await f.call('alice',{...topic,body:'x'.repeat(33000)})).status,413);assert.equal((await f.call('alice',{...topic,profileId:99})).status,400);
 for(let i=0;i<10;i++)assert.equal((await f.call('alice',topic)).status,201);assert.equal((await f.call('alice',topic)).status,429);
 for(let i=0;i<10;i++)await f.call('bob',topic);await f.call('carol',topic);const first=(await f.call(null)).data,second=(await f.call(null,null,{page:2})).data;assert.equal(first.topics.length,20);assert.equal(first.hasMore,true);assert.equal(second.topics.length,1);assert.equal(second.hasMore,false);assert.equal((await f.call(null,null,{q:'%'})).data.topics.length,0);
 for(let i=0;i<50;i++)assert.equal((await f.call('alice',{action:'reply',id:1,body:'Test reply'})).status,201);assert.equal((await f.call('alice',{action:'reply',id:1,body:'Over quota'})).status,429);
 const replies=(await f.call(null,null,{view:'topic',id:1})).data;assert.equal(replies.replies.length,20);assert.equal(replies.hasMore,true);const next=(await f.call(null,null,{view:'topic',id:1,after:replies.replies.at(-1).id})).data;assert.equal(next.replies.length,20);assert.notEqual(next.replies[0].id,replies.replies[0].id);
});
test('category overview totals omit hidden content and include empty categories',async()=>{
 const f=fixture(),id=(await f.call('alice',topic)).data.id;
 await f.call('bob',{action:'reply',id,body:'A visible reply'});
 let overview=(await f.call(null,null,{view:'categories'})).data;
 let c=overview.categories.find(c=>c.id===1);assert.equal(c.topic_count,1);assert.equal(c.reply_count,1);assert.equal(c.latest_id,id);
 assert.equal(overview.categories.find(c=>c.id===2).topic_count,0);
 const detail=(await f.call(null,null,{view:'topic',id})).data;assert.equal(detail.topic.post_count,1);assert.equal(detail.replies[0].post_count,1);
 await f.call('admin',{action:'topicModerate',id,categoryId:1,pinned:false,locked:false,hidden:true});
 overview=(await f.call(null,null,{view:'categories'})).data;c=overview.categories.find(c=>c.id===1);assert.equal(c.topic_count,0);assert.equal(c.reply_count,0);assert.equal(c.latest_id,null);
});
test('deletion enforces ownership and origin; admins can delete any post and topics remove replies',async()=>{
 const f=fixture(),id=(await f.call('alice',topic)).data.id;
 const replyId=(await f.call('bob',{action:'reply',id,body:'Reply to delete'})).data.id;
 assert.equal((await f.call(null,{action:'topicDelete',id})).status,401);
 assert.equal((await f.call('alice',{action:'topicDelete',id},{},'https://evil.test')).status,403);
 assert.equal((await f.call('bob',{action:'topicDelete',id})).status,403);
 assert.equal((await f.call('alice',{action:'replyDelete',id:replyId})).status,403);
 assert.equal((await f.call('bob',{action:'replyDelete',id:replyId})).status,200);
 assert.equal((await f.call(null,null,{view:'topic',id})).data.topic.reply_count,0);
 const second=(await f.call('bob',{action:'reply',id,body:'Another reply'})).data.id;
 assert.equal((await f.call('admin',{action:'replyDelete',id:second})).status,200);
 await f.call('bob',{action:'reply',id,body:'Reply removed with topic'});
 assert.equal((await f.call('alice',{action:'topicDelete',id})).status,200);
 assert.equal((await f.call('admin',null,{view:'topic',id})).status,404);
 const db=await forumDb(f.env);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM forum_replies WHERE topic_id=?').bind(id).first()).n,0);
 const another=(await f.call('alice',topic)).data.id;assert.equal((await f.call('admin',{action:'topicDelete',id:another})).status,200);
});
test('Announcements remains owner-only even if stored category permissions are changed',async()=>{
 const f=fixture(),db=await forumDb(f.env);
 await db.prepare('UPDATE forum_categories SET read_only=0 WHERE id=4').run();
 assert.equal((await f.call('alice',{...topic,categoryId:4})).status,403);
 assert.equal((await f.call('alice',{...topic,action:'news',categoryId:1})).status,403);
 assert.equal((await f.call(null,{...topic,action:'news'})).status,401);
 assert.equal((await f.call(null,null,{view:'categories'})).data.categories.find(c=>c.id===4).read_only,1);
 const id=(await f.call('admin',{...topic,categoryId:4})).data.id;
 assert.equal((await f.call('alice',{action:'reply',id,body:'A member may comment.'})).status,201);
 assert.equal((await f.call('admin',{action:'category',id:4,name:'Announcements',description:'News',position:0,readOnly:false,archived:false})).status,200);
 assert.equal((await db.prepare('SELECT read_only FROM forum_categories WHERE id=4').first()).read_only,1);
});
test('News and Announcements share posts and comments; the homepage follows publication order',async()=>{
 const f=fixture();
 const news=(await f.call('admin',{...topic,action:'news',categoryId:1,title:'Published from News'}));assert.equal(news.status,201);
 const id=news.data.id;
 const forum=(await f.call(null,null,{view:'topic',id})).data;assert.equal(forum.topic.category_id,4);
 const replyId=(await f.call('alice',{action:'reply',id,body:'Comment written on News'})).data.id;
 const detail=(await f.call(null,null,{view:'newsTopic',id})).data;assert.equal(detail.replies[0].id,replyId);assert.equal(detail.topic.reply_count,1);
 assert.equal((await f.call(null,null,{view:'topic',id})).data.replies[0].body,'Comment written on News');
 const newer=(await f.call('admin',{...topic,categoryId:4,title:'Published from Announcements'})).data.id;
 const general=(await f.call('alice',topic)).data.id;
 let feed=(await f.call(null,null,{view:'news'})).data.articles;
 assert.ok(feed.some(a=>a.id===id));assert.ok(feed.some(a=>a.id===newer));assert.ok(!feed.some(a=>a.id===general));
 assert.equal((await f.call(null,null,{view:'newsTopic',id:general})).status,404);
 await f.call('alice',{action:'reply',id,body:'Later comment on older article'});
 assert.equal((await f.call(null,null,{view:'latestNews'})).data.article.id,newer);
 const mod={action:'topicModerate',id:newer,categoryId:4,pinned:false,locked:false,hidden:true};await f.call('admin',mod);
 assert.equal((await f.call(null,null,{view:'latestNews'})).data.article.id,id);
 assert.equal((await f.call(null,null,{view:'newsTopic',id:newer})).status,404);
 await f.call('admin',{...mod,hidden:false});assert.equal((await f.call(null,null,{view:'latestNews'})).data.article.id,newer);
 await f.call('admin',{action:'topicDelete',id:newer});assert.equal((await f.call(null,null,{view:'latestNews'})).data.article.id,id);
 await f.call('admin',{action:'replyModerate',id:replyId,hidden:true});assert.ok(!(await f.call(null,null,{view:'newsTopic',id})).data.replies.some(r=>r.id===replyId));
 await f.call('admin',{...mod,id,hidden:false,categoryId:1});assert.ok(!(await f.call(null,null,{view:'news'})).data.articles.some(a=>a.id===id));
});
test('Historical release imports once, keeps its date and legacy link, and is not resurrected after deletion',async()=>{
 const f=fixture();const feed=(await f.call(null,null,{view:'news'})).data.articles;
 assert.equal(feed.length,1);assert.equal(feed[0].title,'The Kollection 2.5.0 is out now');assert.match(feed[0].created_at,/^2026-08-08/);assert.match(feed[0].body,/324 catalogs/);
 const legacy=(await f.call(null,null,{view:'newsLegacy'})).data;assert.equal(legacy.topic.id,feed[0].id);
 await f.call('alice',{action:'reply',id:feed[0].id,body:'A comment on the existing release'});
 assert.equal((await f.call(null,null,{view:'newsLegacy'})).data.topic.reply_count,1);
 for(let i=0;i<3;i++)assert.equal((await f.call(null,null,{view:'news'})).data.articles.length,1);
 assert.equal((await f.call(null,null,{category:4})).data.topics.length,1);
 await f.call('admin',{action:'topicDelete',id:feed[0].id});
 assert.equal((await f.call(null,null,{view:'news'})).data.articles.length,0);
 assert.equal((await f.call(null,null,{view:'latestNews'})).data.article,null);
 assert.equal((await f.call(null,null,{view:'newsLegacy'})).status,404);
});
test('editing enforces ownership, origin and the exact 24-hour cutoff without resetting dates',async()=>{
 const f=fixture(),id=(await f.call('alice',topic)).data.id;
 const rid=(await f.call('alice',{action:'reply',id,body:'Original reply'})).data.id;
 const db=await forumDb(f.env),realNow=Date.now,fixed=realNow();
 Date.now=()=>fixed;
 try{
  const original=new Date(fixed-86400000+1).toISOString();
  await db.prepare('UPDATE forum_topics SET created_at=?,updated_at=? WHERE id=?').bind(original,original,id).run();
  await db.prepare('UPDATE forum_replies SET created_at=? WHERE id=?').bind(original,rid).run();
  const edit={action:'topicEdit',id,title:'Edited title',body:'Edited **body**'};
  assert.equal((await f.call(null,edit)).status,401);
  assert.equal((await f.call('alice',edit,{},'https://evil.test')).status,403);
  assert.equal((await f.call('bob',edit)).status,403);
  assert.equal((await f.call('bob',{action:'replyEdit',id:rid,body:'Stolen reply'})).status,403);
  assert.equal((await f.call('alice',{...edit,title:'x'})).status,400);
  assert.equal((await f.call('alice',edit)).status,200);
  assert.equal((await f.call('alice',{action:'replyEdit',id:rid,body:'Edited reply'})).status,200);
  let d=(await f.call('alice',null,{view:'topic',id})).data;
  assert.equal(d.topic.can_edit,true);assert.equal(d.replies[0].can_edit,true);
  assert.equal(d.topic.created_at,original);assert.equal(d.topic.updated_at,original);
  assert.equal(d.topic.title,'Edited title');assert.equal(d.replies[0].body,'Edited reply');
  assert.equal((await f.call('bob',null,{view:'topic',id})).data.topic.can_edit,false);
  Date.now=()=>fixed+1;
  assert.equal((await f.call('alice',edit)).status,403);
  assert.equal((await f.call('alice',{action:'replyEdit',id:rid,body:'Too late'})).status,403);
  d=(await f.call('alice',null,{view:'topic',id})).data;assert.equal(d.topic.can_edit,false);assert.equal(d.replies[0].can_edit,false);
  assert.equal((await f.call('admin',edit)).status,200);
  assert.equal((await f.call('admin',{action:'replyEdit',id:rid,body:'Admin edit'})).status,200);
 }finally{Date.now=realNow;}
});
test('admin edits legacy News and all shared views reflect the same title and body',async()=>{
 const f=fixture(),legacy=(await f.call('admin',null,{view:'newsLegacy'})).data.topic;
 assert.equal(legacy.can_edit,true);
 assert.equal((await f.call('admin',{action:'topicEdit',id:legacy.id,title:'Updated release article',body:'Updated **release** details'})).status,200);
 for(const view of ['topic','newsTopic']){const d=(await f.call(null,null,{view,id:legacy.id})).data.topic;assert.equal(d.title,'Updated release article');assert.equal(d.body,'Updated **release** details');assert.equal(d.created_at,legacy.created_at);}
 assert.equal((await f.call(null,null,{view:'latestNews'})).data.article.title,'Updated release article');
 assert.equal((await f.call(null,null,{view:'news'})).data.articles[0].body,'Updated **release** details');
 const id=(await f.call('alice',topic)).data.id,member=(await f.call('alice',null,{view:'self'})).data.myMemberId;
 await f.call('admin',{action:'memberModerate',id:member,banned:true,clearAbout:false});
 assert.equal((await f.call('alice',{action:'topicEdit',id,title:'Banned update',body:'Not allowed'})).status,403);
});
test('optional GitHub release URLs persist, validate, edit and clear across News and Announcements',async()=>{
 const f=fixture(),url='https://github.com/Kaoxt/The-Kollection/releases/tag/v2.5.0';
 for(const releaseUrl of ['javascript:alert(1)','https://github.com.evil.test/a/b/releases','https://github.com/a/b/issues/1','https://user@github.com/a/b/releases','http://github.com/a/b/releases'])assert.equal((await f.call('admin',{...topic,action:'news',releaseUrl})).status,400);
 assert.equal((await f.call('alice',{...topic,releaseUrl:url})).status,403);
 const created=await f.call('admin',{...topic,action:'news',releaseUrl:url});assert.equal(created.status,201);const id=created.data.id;
 for(const view of ['topic','newsTopic'])assert.equal((await f.call(null,null,{view,id})).data.topic.github_release_url,url);
 assert.equal((await f.call(null,null,{view:'news'})).data.articles.find(t=>t.id===id).github_release_url,url);
 const edit={action:'topicEdit',id,title:'Updated release title',body:'Updated release notes'};
 await f.call('admin',edit);assert.equal((await f.call(null,null,{view:'topic',id})).data.topic.github_release_url,url);
 const next='https://github.com/Kaoxt/The-Kollection/releases/latest';await f.call('admin',{...edit,releaseUrl:next});assert.equal((await f.call(null,null,{view:'newsTopic',id})).data.topic.github_release_url,next);
 assert.equal((await f.call('admin',{...edit,releaseUrl:'https://example.com'})).status,400);
 await f.call('admin',{...edit,releaseUrl:''});assert.equal((await f.call(null,null,{view:'newsTopic',id})).data.topic.github_release_url,'');
});
test('existing forum table gains release URL without losing historical content',async()=>{
 const f=fixture();
 await f.env.DB.prepare("CREATE TABLE forum_topics (id INTEGER PRIMARY KEY AUTOINCREMENT,member_id TEXT,category_id INTEGER,title TEXT,body TEXT,pinned INTEGER DEFAULT 0,locked INTEGER DEFAULT 0,hidden INTEGER DEFAULT 0,created_at TEXT,updated_at TEXT)").run();
 await f.env.DB.prepare("INSERT INTO forum_topics(member_id,category_id,title,body,created_at,updated_at) VALUES('old',4,'Existing news','Original body','2026-01-01','2026-01-01')").run();
 const db=await forumDb(f.env),old=await db.prepare('SELECT * FROM forum_topics WHERE id=1').first();assert.equal(old.body,'Original body');assert.equal(old.github_release_url,'');
 assert.equal((await f.call('admin',{...topic,action:'news',releaseUrl:'https://github.com/Kaoxt/site/releases'})).status,201);
});
test('GitHub release links are exclusive to Announcements and removed when moving a topic out',async()=>{
 const f=fixture(),releaseUrl='https://github.com/Kaoxt/site/releases/latest';
 assert.equal((await f.call('admin',{...topic,releaseUrl})).status,400);
 const general=(await f.call('admin',topic)).data.id;
 assert.equal((await f.call('admin',{action:'topicEdit',id:general,title:'General edited',body:'Body edited',releaseUrl})).status,400);
 const id=(await f.call('admin',{...topic,categoryId:4,releaseUrl})).data.id;
 assert.equal((await f.call(null,null,{view:'topic',id})).data.topic.github_release_url,releaseUrl);
 await f.call('admin',{action:'topicModerate',id,categoryId:1,pinned:false,locked:false,hidden:false});
 assert.equal((await f.call(null,null,{view:'topic',id})).data.topic.github_release_url,'');
});
test('likes are unique, reversible, authenticated and counted on public and account profiles',async()=>{
 const f=fixture(),id=(await f.call('alice',topic)).data.id,rid=(await f.call('alice',{action:'reply',id,body:'Reply with likes'})).data.id;
 const like={action:'like',kind:'topic',id,liked:true};
 assert.equal((await f.call(null,like)).status,401);assert.equal((await f.call('alice',like)).status,403);assert.equal((await f.call('bob',like,{},'https://evil.test')).status,403);
 assert.equal((await f.call('bob',like)).data.like_count,1);assert.equal((await f.call('bob',like)).data.like_count,1);
 await f.call('carol',like);await f.call('bob',{...like,kind:'reply',id:rid});
 let d=(await f.call('bob',null,{view:'topic',id})).data;assert.equal(d.topic.like_count,2);assert.equal(d.topic.liked,true);assert.equal(d.replies[0].like_count,1);
 assert.equal((await f.call(null,null,{view:'topic',id})).data.topic.liked,false);
 const member=d.topic.member_id;
 assert.equal((await f.call(null,null,{view:'member',id:member})).data.member.likes_received,3);
 assert.equal((await f.call('alice',null,{view:'self'})).data.stats.likes_received,3);
 await f.call('bob',{...like,liked:false});assert.equal((await f.call('alice',null,{view:'self'})).data.stats.likes_received,2);
 await f.call('admin',{action:'replyModerate',id:rid,hidden:true});assert.equal((await f.call('alice',null,{view:'self'})).data.stats.likes_received,1);assert.equal((await f.call('bob',{...like,kind:'reply',id:rid})).status,404);
 await f.call('admin',{action:'topicModerate',id,categoryId:1,pinned:false,locked:false,hidden:true});assert.equal((await f.call('alice',null,{view:'self'})).data.stats.likes_received,0);
 await f.call('admin',{action:'topicDelete',id});const db=await forumDb(f.env);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM forum_likes').first()).n,0);
});
test('shared reply links load the requested reply beyond the first page',async()=>{
 const f=fixture(),id=(await f.call('alice',topic)).data.id;let rid;
 for(let i=0;i<25;i++)rid=(await f.call('bob',{action:'reply',id,body:'Reply '+i})).data.id;
 assert.notEqual((await f.call(null,null,{view:'topic',id})).data.replies.at(-1).id,rid);
 assert.equal((await f.call(null,null,{view:'topic',id,reply:rid})).data.replies[0].id,rid);
});
test('follow persists uniquely, tracks new replies, stays private and clears on unfollow or deletion',async()=>{
 const f=fixture(),id=(await f.call('alice',topic)).data.id,follow={action:'follow',id,following:true};
 assert.equal((await f.call(null,follow)).status,401);assert.equal((await f.call('bob',follow,{},'https://evil.test')).status,403);
 assert.equal((await f.call('bob',follow)).data.follower_count,1);assert.equal((await f.call('bob',follow)).data.follower_count,1);
 assert.equal((await f.call('bob',null,{view:'topic',id})).data.topic.following,1);
 assert.equal((await f.call('alice',null,{view:'topic',id})).data.topic.following,0);
 const rid=(await f.call('alice',{action:'reply',id,body:'New reply for followers'})).data.id;
 let list=(await f.call('bob',null,{view:'followed'})).data;assert.equal(list.topics[0].unread_count,1);assert.equal(list.topics[0].first_unread,rid);
 assert.equal((await f.call('bob',null,{view:'self'})).data.follows.unread,1);
 assert.equal((await f.call('carol',null,{view:'followed'})).data.topics.length,0);assert.equal((await f.call(null,null,{view:'followed'})).status,401);
 await f.call('bob',null,{view:'topic',id,reply:rid});assert.equal((await f.call('bob',null,{view:'self'})).data.follows.unread,0);
 await f.call('admin',{action:'topicModerate',id,categoryId:1,pinned:false,locked:false,hidden:true});assert.equal((await f.call('bob',follow)).status,404);assert.equal((await f.call('bob',null,{view:'followed'})).data.topics.length,0);
 await f.call('admin',{action:'topicModerate',id,categoryId:1,pinned:false,locked:false,hidden:false});
 assert.equal((await f.call('bob',{...follow,following:false})).data.follower_count,0);assert.equal((await f.call('bob',null,{view:'followed'})).data.topics.length,0);
 await f.call('bob',follow);await f.call('admin',{action:'topicDelete',id});const db=await forumDb(f.env);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM forum_follows').first()).n,0);
});
