(() => {
  const {esc,api,date,author,rows,submit}=window.KollectionForum,$=id=>document.getElementById(id),root=$('forum-content');let version=0;
  const status='<p data-status class="issue-error" role="alert" tabindex="-1"></p>';
  const bind=(form,build)=>form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;submit(form,async()=>{await api({},build(Object.fromEntries(new FormData(form))));await load();$('admin-feedback').textContent='Changes saved.';});});
  const categoryForm=c=>`<form class="issue-form" data-category="${c.id||''}"><label>Name<input name="name" maxlength="60" required value="${esc(c.name)}"></label><label>Description<input name="description" maxlength="240" value="${esc(c.description)}"></label><label>Order<input type="number" name="position" min="-9999" max="9999" required value="${c.position||0}"></label><label><input type="checkbox" name="readOnly" ${c.read_only?'checked':''}>Only admins can start topics</label><label><input type="checkbox" name="archived" ${c.archived?'checked':''}>Archive category (keep existing discussions)</label>${status}<button>${c.id?'Save category':'Add category'}</button></form>`;
  function chrome(tab){return `<div class="forum-toolbar"><a href="/admin">← Admin panel</a><a href="/discussions">View discussions →</a></div><nav class="forum-links forum-admin-nav" aria-label="Forum administration">${['categories','topics','members'].map(k=>`<a href="#${k}" ${tab===k?'aria-current="page"':''}>${k[0].toUpperCase()+k.slice(1)}</a>`).join('')}</nav><p id="admin-feedback" role="status"></p>`;}
  function paging(data,tab,params){return `<nav class="issue-pagination" aria-label="Admin pages">${data.page>1?`<a href="#${tab}?${esc(new URLSearchParams({...Object.fromEntries(params),page:data.page-1}))}">Previous</a>`:''}<span>Page ${data.page}</span>${data.hasMore?`<a href="#${tab}?${esc(new URLSearchParams({...Object.fromEntries(params),page:data.page+1}))}">Next</a>`:''}</nav>`;}
  async function load(){const n=++version, [raw,query='']=location.hash.slice(1).split('?'),tab=['topics','members'].includes(raw)?raw:'categories',params=new URLSearchParams(query);root.setAttribute('aria-busy','true');$('forum-error').textContent='';
    try{const d=await api({...Object.fromEntries(params),view:tab==='topics'?'list':'admin',...(tab==='topics'?{moderation:1}:{})});if(n!==version)return;root.innerHTML=chrome(tab);
      if(tab==='categories'){
        root.insertAdjacentHTML('beforeend',`<dl class="forum-stats"><div><dt>Discussions</dt><dd>${d.stats.topics}</dd></div><div><dt>Replies</dt><dd>${d.stats.replies}</dd></div><div><dt>Members</dt><dd>${d.stats.members}</dd></div></dl><form id="posting-settings" class="issue-card issue-form"><label><input type="checkbox" name="postingOpen" ${d.postingOpen?'checked':''}>Allow members to post</label><p class="issue-note">Turn this off to make the forum read-only. Administrators can still post.</p>${status}<button>Save posting settings</button></form><div class="forum-admin-grid">${d.categories.map(c=>`<section class="issue-card"><details><summary>${esc(c.name)} ${c.archived?'· Archived':''}</summary>${categoryForm(c)}</details></section>`).join('')}<section class="issue-card"><details open><summary>Add a category</summary>${categoryForm({})}</details></section></div>`);
        bind($('posting-settings'),f=>({action:'settings',postingOpen:f.postingOpen==='on'}));
        root.querySelectorAll('[data-category]').forEach(form=>bind(form,f=>({...f,action:'category',id:form.dataset.category||null,position:Number(f.position),archived:f.archived==='on',readOnly:f.readOnly==='on'})));
      }else{
        root.insertAdjacentHTML('beforeend',`<form id="admin-search" class="issue-filters"><label class="issue-search">Search ${tab}<input type="search" name="q" maxlength="80" value="${esc(params.get('q'))}" placeholder="${tab==='topics'?'Discussion title':'Display name'}"></label><button>Search</button></form>`);
        $('admin-search').onsubmit=e=>{e.preventDefault();location.hash=tab+'?'+new URLSearchParams(new FormData(e.currentTarget));};
        if(tab==='topics')root.insertAdjacentHTML('beforeend',`<p class="issue-note">Open a discussion to move it, pin it, lock it, or hide and restore its posts. Hidden discussions appear here for moderation.</p><div class="issue-results">${rows(d.topics)}</div>${paging(d,tab,params)}`);
        else{
          root.insertAdjacentHTML('beforeend',`${d.members.map(m=>`<article class="issue-card"><div class="issue-meta">${author(m)}<span>${m.topic_count+m.reply_count} posts · Joined ${date(m.created_at)}</span>${m.banned?'<span class="issue-badge">Posting restricted</span>':''}</div><p class="issue-body">${esc(m.about||'No About me information.')}</p><form class="issue-form" data-member="${m.member_id}"><label><input type="checkbox" name="banned" ${m.banned?'checked':''}>Restrict posting</label><label><input type="checkbox" name="clearAbout">Clear About me</label>${status}<button>Save member settings</button></form></article>`).join('')||'<p>No members found.</p>'}${paging(d,tab,params)}`);
          root.querySelectorAll('[data-member]').forEach(form=>bind(form,f=>({action:'memberModerate',id:form.dataset.member,banned:f.banned==='on',clearAbout:f.clearAbout==='on'})));
        }
      }
    }catch(e){if(n!==version)return;root.innerHTML='<a href="/account?next=%2Fadmin-forum">Sign in with your administrator account</a><p><button id="retry-admin">Try again</button></p>';$('forum-error').textContent=e.message;$('retry-admin').onclick=load;}finally{if(n===version)root.removeAttribute('aria-busy');}}
  window.addEventListener('hashchange',load);window.addEventListener('kollection:nuvio-signed-out',load);window.addEventListener('kollection:nuvio-signed-in',load);load();
})();
