(() => {
  const {esc,api,date,author,flags,rows,submit}=window.KollectionForum,$=id=>document.getElementById(id),root=$('forum-content');
  let version=0;
  const backIcon='<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m12 19-7-7 7-7M5 12h14"/></svg>';
  const back=(href='/discussions',label='All discussions')=>`<a class="forum-back" href="${href}">${backIcon}<span>${esc(label)}</span></a>`;
  const rich=body=>window.KollectionForumEditor.render(body);
  const editors=()=>window.KollectionForumEditor.attach(root);
  const removable=(post,d)=>d.isAdmin||!!d.myMemberId&&d.myMemberId===post.member_id;
  const deleteButton=(post,d,kind)=>removable(post,d)?`<button type="button" class="forum-delete" data-delete="${kind}" data-id="${post.id}">Delete ${kind==='topic'?'discussion':'reply'}</button>`:'';
  const postHtml=(post,d,kind)=>`<article class="forum-post" id="${kind}-${post.id}"><aside class="forum-post-author">${author(post)}<span class="issue-note">${Number(post.post_count)||0} posts</span></aside><div class="forum-post-main"><div class="forum-post-meta"><span>Posted ${date(post.created_at)}</span>${post.hidden?'<span class="issue-badge">Hidden</span>':''}${deleteButton(post,d,kind)}</div><div class="forum-rich">${rich(post.body)}</div>${kind==='reply'&&d.isAdmin?`<button type="button" data-reply="${post.id}" data-hidden="${post.hidden?0:1}">${post.hidden?'Restore reply':'Hide reply'}</button>`:''}</div></article>`;
  function bindDeletes(d){root.querySelectorAll('[data-delete]').forEach(button=>button.onclick=async()=>{
    const kind=button.dataset.delete;
    if(!confirm(kind==='topic'?'Delete this discussion and all its replies? This cannot be undone.':'Delete this reply? This cannot be undone.'))return;
    button.disabled=true;
    try{await api({},{action:kind+'Delete',id:button.dataset.id});if(kind==='topic')location.hash='list?category='+d.topic.category_id;else await load();}catch(e){$('forum-error').textContent=e.message;$('forum-error').focus();button.disabled=false;}
  });}
  function categoriesView(d){
    root.innerHTML=`<div class="forum-toolbar"><div class="forum-links">${d.myMemberId?`<a href="#member/${d.myMemberId}">My profile</a>`:''}<a href="#list">All topics</a><a href="/issues">Report an issue</a>${d.isAdmin?'<a href="/admin-forum">Manage forum</a>':''}</div><button id="new-topic" class="issue-primary" ${canWrite(d)?'':'disabled'}>New discussion</button></div>${note(d)?`<p class="issue-note">${note(d)}</p>`:''}<form id="forum-search" class="issue-filters"><label class="issue-search">Search discussions<input name="q" type="search" maxlength="100" placeholder="Search titles"></label><button>Search</button></form><section id="forum-list" class="issue-results"><div class="forum-section-title"><h2>Community categories</h2></div>${d.categories.map(c=>`<article class="forum-category"><div class="forum-category-icon" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8z"/></svg></div><div class="forum-category-main"><h3><a href="#list?category=${c.id}">${esc(c.name)}</a>${c.archived?' <span class="issue-badge">Archived</span>':c.read_only?' <span class="issue-badge">Admin topics</span>':''}</h3><p>${esc(c.description)}</p>${c.latest_id?`<div class="forum-latest"><a href="#topic/${c.latest_id}">${esc(c.latest_title)}</a><span>${date(c.latest_at)}</span></div>`:'<span class="issue-note">No discussions yet</span>'}</div><div class="forum-category-count"><strong>${c.topic_count+c.reply_count}</strong><span>posts</span><small>${c.topic_count} topics</small></div></article>`).join('')}</section>`;
    $('new-topic').onclick=()=>newTopic(d);$('forum-search').onsubmit=e=>{e.preventDefault();location.hash='list?'+new URLSearchParams(new FormData(e.currentTarget));};
  }
  const options=(cats,value,filter=false,admin=false)=>cats.filter(c=>!filter||(!c.archived&&(!c.read_only||admin))).map(c=>`<option value="${c.id}" ${Number(value)===c.id?'selected':''}>${esc(c.name)}${c.archived?' (archived)':''}</option>`).join('');
  const pager=(data,link)=>`<nav class="issue-pagination" aria-label="Discussion pages">${data.page>1?`<a href="${link(data.page-1)}">← Previous</a>`:''}<span>Page ${data.page}</span>${data.hasMore?`<a href="${link(data.page+1)}">Next →</a>`:''}</nav>`;
  const status='<p data-status class="issue-error" role="alert" tabindex="-1"></p>';
  const canWrite=d=>d.canPost&&(d.postingOpen||d.isAdmin);
  const note=d=>!d.authenticated?`<a href="/account?next=${encodeURIComponent('/discussions'+location.hash)}">Sign in with Nuvio</a> to join the conversation.`:!d.canPost?'Posting is disabled for your account.':!d.postingOpen?'The forum is temporarily read-only.':'';
  function bindPost(form,data,success){form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;submit(form,async()=>{const result=await api({},data(Object.fromEntries(new FormData(form))));await success(result);});});}
  function newTopic(d){
    if($('new-topic-form'))return;
    const section=document.createElement('section');section.className='issue-card';section.innerHTML=`<form id="new-topic-form" class="issue-form"><h2>New discussion</h2><label>Category<select name="categoryId" required>${options(d.categories,d.selectedCategory,true,d.isAdmin)}</select></label><label>Title<input name="title" minlength="5" maxlength="160" required placeholder="What would you like to discuss?"></label><label>Message<textarea name="body" minlength="2" maxlength="10000" rows="6" required></textarea></label><p class="issue-note">Posts are public. Keep passwords and API keys private.</p>${status}<div class="issue-form-actions"><button type="button" id="cancel-topic">Cancel</button><button class="issue-primary">Post discussion</button></div></form>`;
    $('forum-list').before(section);$('cancel-topic').onclick=()=>section.remove();editors();section.querySelector('input').focus();
    bindPost($('new-topic-form'),f=>({...f,action:'topic'}),r=>{location.hash='topic/'+r.id;});
  }
  function listView(d,params){
    const category=d.categories.find(c=>c.id===Number(params.get('category')));d.selectedCategory=category?.id;
    const link=p=>'#list?'+new URLSearchParams({...Object.fromEntries(params),page:p});
    root.innerHTML=`${back()}<header class="issue-card forum-category-header"><h2>${esc(category?.name||'All topics')}</h2><p>${esc(category?.description||'The latest conversations from every category.')}</p></header><div class="forum-toolbar"><div class="forum-links">${d.myMemberId?`<a href="#member/${d.myMemberId}">My profile</a>`:''}<a href="/issues">Report an issue</a>${d.isAdmin?'<a href="/admin-forum">Manage forum</a>':''}</div><button id="new-topic" class="issue-primary" ${canWrite(d)&&(!category||!category.archived&&(!category.read_only||d.isAdmin))?'':'disabled'}>New discussion</button></div>${note(d)?`<p class="issue-note">${note(d)}</p>`:''}<form id="forum-filter" class="issue-filters"><label class="issue-search">Search discussions<input name="q" type="search" maxlength="100" value="${esc(params.get('q'))}" placeholder="Search titles"></label><label>Category<select name="category"><option value="">All categories</option>${options(d.categories,params.get('category'))}</select></label><button>Search</button></form><div id="forum-list" class="issue-results">${rows(d.topics)}</div>${pager(d,link)}`;
    $('forum-filter').onsubmit=e=>{e.preventDefault();location.hash='list?'+new URLSearchParams(new FormData(e.currentTarget));};$('new-topic').onclick=()=>newTopic(d);
  }
  const replyHtml=(r,d)=>postHtml(r,d,'reply');
  function bindModeration(){root.querySelectorAll('[data-reply]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api({},{action:'replyModerate',id:b.dataset.reply,hidden:b.dataset.hidden==='1'});await load();}catch(e){$('forum-error').textContent=e.message;b.disabled=false;}});}
  function topicView(d){
    const t=d.topic;document.title=t.title+' | Discussions';
    root.innerHTML=`<nav class="forum-breadcrumbs" aria-label="Discussion navigation">${back()}<span aria-hidden="true">/</span><a href="#list?category=${t.category_id}">${esc(t.category_name)}</a></nav><article class="issue-card"><div class="issue-meta">${flags(t)}<span>${esc(t.category_name)}</span></div><h2 class="issue-detail-title">${esc(t.title)}</h2><div class="issue-meta">${author(t)}<span>${date(t.created_at)}</span></div>${d.isAdmin?`<details><summary>Manage discussion</summary><form id="moderate-topic" class="issue-form"><label>Category<select name="categoryId">${options(d.categories,t.category_id)}</select></label><div class="forum-controls">${['pinned','locked','hidden'].map(k=>`<label><input type="checkbox" name="${k}" ${t[k]?'checked':''}>${k[0].toUpperCase()+k.slice(1)}</label>`).join('')}</div>${status}<button>Save changes</button></form></details>`:''}</article>${postHtml(t,d,'topic')}<h2>Replies <span class="issue-badge">${t.reply_count}</span></h2><div id="forum-replies">${d.replies.map(r=>replyHtml(r,d)).join('')||'<p>No replies yet.</p>'}</div><button id="more-replies" ${d.hasMore?'':'hidden'}>Load more replies</button>${canWrite(d)&&(!t.locked||d.isAdmin)&&!t.hidden?`<form id="reply-form" class="issue-card issue-form"><label>Add a reply<textarea name="body" minlength="2" maxlength="10000" rows="4" required></textarea></label>${status}<div class="issue-form-actions"><button class="issue-primary">Post reply</button></div></form>`:`<p class="issue-note">${t.hidden?'This discussion is hidden.':t.locked?'This discussion is locked.':note(d)}</p>`}`;
    bindPost($('moderate-topic'),f=>({action:'topicModerate',id:t.id,categoryId:f.categoryId,pinned:f.pinned==='on',locked:f.locked==='on',hidden:f.hidden==='on'}),load);
    bindPost($('reply-form'),f=>({...f,action:'reply',id:t.id}),async()=>{await load();const message=document.createElement('p');message.className='issue-note';message.setAttribute('role','status');message.textContent='Your reply was posted.';$('reply-form')?.before(message);});
    let after=d.replies.at(-1)?.id||0;const route=version;
    $('more-replies').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{const more=await api({view:'topic',id:t.id,after});if(route!==version)return;$('forum-replies').insertAdjacentHTML('beforeend',more.replies.map(r=>replyHtml(r,d)).join(''));after=more.replies.at(-1)?.id||after;b.hidden=!more.hasMore;bindModeration();bindDeletes(d);}catch(e){$('forum-error').textContent=e.message;}finally{b.disabled=false;}};bindModeration();bindDeletes(d);editors();
  }
  function memberView(d,params){const m=d.member;document.title=m.author+' | The Kollection';root.innerHTML=`<div class="forum-toolbar">${back()}${d.myMemberId===m.member_id?'<a href="/account#community-profile">Edit profile</a>':''}</div><article class="issue-card"><div class="forum-profile-head">${window.KollectionIssueMedia.avatar(m.author,m.avatar_url,m.avatar_color)}<div><h2>${esc(m.author)}</h2><p class="issue-note">Joined ${date(m.created_at)}</p></div></div><dl class="forum-stats"><div><dt>Posts</dt><dd>${m.topic_count+m.reply_count}</dd></div><div><dt>Discussions</dt><dd>${m.topic_count}</dd></div><div><dt>Replies</dt><dd>${m.reply_count}</dd></div></dl><h2>About me</h2><p class="issue-body">${esc(m.about||'Nothing shared yet.')}</p></article><h2>Discussions started</h2><div class="issue-results">${rows(d.topics)}</div>${pager(d,p=>'#member/'+m.member_id+'?page='+p)}`;}
  async function load(){const current=++version;$('forum-error').textContent='';root.setAttribute('aria-busy','true');const [route,query='']=location.hash.slice(1).split('?'),params=new URLSearchParams(query),[view,key]=route.split('/');
    try{const data=await api({...Object.fromEntries(params),view:view==='topic'||view==='member'?view:!view?'categories':'list',...(key?{id:key}:{})});if(current!==version)return;document.title='Discussions | The Kollection';if(view==='topic')topicView(data);else if(view==='member')memberView(data,params);else if(!view)categoriesView(data);else listView(data,params);}catch(e){if(current!==version)return;root.innerHTML=back()+'<p><button id="retry-forum">Try again</button></p>';$('forum-error').textContent=e.message;$('retry-forum').onclick=load;}finally{if(current===version)root.removeAttribute('aria-busy');}}
  window.addEventListener('hashchange',()=>{load();});window.addEventListener('kollection:nuvio-signed-out',load);window.addEventListener('kollection:nuvio-signed-in',load);load();
})();
