(() => {
  const {esc,api,date,author,flags,rows,submit}=window.KollectionForum,$=id=>document.getElementById(id),root=$('forum-content');
  const newsPage=root.dataset.news==='true';
  const forumPage=newsPage?null:root.closest('.secondary-page');
  const pagePath=newsPage?'/news.html':'/discussions';
  let version=0;
  const backIcon='<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m12 19-7-7 7-7M5 12h14"/></svg>';
  const back=(href=pagePath,label=newsPage?'All news':'All forums')=>`<a class="forum-back" href="${href}">${backIcon}<span>${esc(label)}</span></a>`;
  const releaseField=(value='')=>`<label>GitHub release URL (optional)<input name="releaseUrl" type="url" maxlength="2048" placeholder="https://github.com/owner/repo/releases/tag/v1.0" value="${esc(value)}"></label>`;
  const releaseLink=post=>post.category_id===4&&post.github_release_url?`<a class="news-github-link" href="${esc(post.github_release_url)}" target="_blank" rel="noopener noreferrer">Open on GitHub</a>`:'';
  const rich=body=>window.KollectionForumEditor.render(body);
  const editors=()=>window.KollectionForumEditor.attach(root);
  const removable=(post,d)=>d.isAdmin||!!d.myMemberId&&d.myMemberId===post.member_id;
  const deleteButton=(post,d,kind)=>removable(post,d)?`<button type="button" class="forum-delete" data-delete="${kind}" data-id="${post.id}">Delete ${kind==='topic'?'discussion':'reply'}</button>`:'';
  const postHtml=(post,d,kind)=>`<article class="forum-post" id="${kind}-${post.id}"><header class="forum-post-bar"><span class="forum-post-bar-author">${esc(post.author)}</span><div class="forum-post-meta"><span>Posted ${date(post.created_at)}</span>${kind==='reply'&&post.hidden?'<span class="issue-badge">Hidden</span>':''}<div class="forum-post-actions">${post.can_edit?`<button type="button" data-edit="${kind}" data-id="${post.id}">Edit ${kind==='topic'&&newsPage?'news':'post'}</button>`:''}${kind==='topic'&&d.isAdmin?'<button type="button" id="manage-topic-toggle" aria-expanded="false" aria-controls="topic-management">Manage</button>':''}${kind==='reply'&&d.isAdmin?`<button type="button" data-reply="${post.id}" data-hidden="${post.hidden?0:1}">${post.hidden?'Restore':'Hide'}</button>`:''}${deleteButton(post,d,kind)}</div></div></header><aside class="forum-post-author">${author(post)}<span class="issue-note">${Number(post.post_count)||0} posts</span></aside><div class="forum-post-main">${kind==='topic'?`${d.isAdmin?`<section id="topic-management" class="forum-management" hidden><h3>Manage discussion</h3><form id="moderate-topic" class="issue-form"><label>Category<select name="categoryId">${options(d.categories,post.category_id)}</select></label><div class="forum-controls">${['pinned','locked','hidden'].map(k=>`<label><input type="checkbox" name="${k}" ${post[k]?'checked':''}>${k[0].toUpperCase()+k.slice(1)}</label>`).join('')}</div>${status}<button>Save changes</button></form></section>`:''}`:''}<div class="forum-rich">${rich(post.body)}</div>${kind==='topic'?`<div data-release-link>${releaseLink(post)}</div>`:''}${socialFooter(post,d,kind)}</div></article>`;
  const postUrl=(kind,id,topicId)=>location.origin+'/discussions#topic/'+topicId+(kind==='reply'?'?reply='+id:'');
  const socialFooter=(post,d,kind)=>`<footer class="forum-post-footer"><div><button type="button" data-quote="${kind}" data-id="${post.id}" ${canWrite(d)&&(!d.topic.locked||d.isAdmin)&&!d.topic.hidden?'':'disabled'}>Quote</button><button type="button" data-share="${kind}" data-id="${post.id}">Share</button></div><button type="button" class="forum-like" data-like="${kind}" data-id="${post.id}" aria-pressed="${!!post.liked}" ${!d.canPost||d.myMemberId===post.member_id?'disabled':''} title="${!d.authenticated?'Sign in to like posts':d.myMemberId===post.member_id?'Likes received on your post':'Like this post'}"><span aria-hidden="true">♡</span> <span data-like-label>${post.liked?'Liked':'Like'}</span> <span data-like-count>${post.like_count||0}</span></button></footer>`;
  function bindSocial(d){
    const find=(kind,id)=>kind==='topic'?d.topic:d.replies.find(r=>String(r.id)===String(id));
    root.querySelectorAll('[data-like]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const post=find(b.dataset.like,b.dataset.id),r=await api({},{action:'like',kind:b.dataset.like,id:post.id,liked:!post.liked});Object.assign(post,r);b.setAttribute('aria-pressed',String(r.liked));b.querySelector('[data-like-label]').textContent=r.liked?'Liked':'Like';b.querySelector('[data-like-count]').textContent=r.like_count;}catch(e){$('forum-error').textContent=e.message;}finally{b.disabled=false;}});
    root.querySelectorAll('[data-quote]').forEach(b=>b.onclick=()=>{const post=find(b.dataset.quote,b.dataset.id),input=$('reply-form')?.querySelector('[name=body]');if(!input)return;const quote='> '+post.author.replace(/[\r\n]/g,' ')+' wrote:\n'+post.body.split('\n').map(line=>'> '+line).join('\n')+'\n\n';if(input.value.length+quote.length+2>input.maxLength){$('forum-error').textContent='This quote is too long for the reply. Please shorten your draft first.';return;}input.value+=(input.value?'\n\n':'')+quote;input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollIntoView({block:'center',behavior:'smooth'});input.focus();input.setSelectionRange(input.value.length,input.value.length);});
    root.querySelectorAll('[data-share]').forEach(b=>b.onclick=async()=>{const url=postUrl(b.dataset.share,b.dataset.id,d.topic.id);try{if(navigator.share)await navigator.share({title:d.topic.title,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);b.textContent='Link copied';}else window.prompt('Copy this post link',url);}catch(e){if(e.name!=='AbortError')window.prompt('Copy this post link',url);}});
  }
  function bindDeletes(d){root.querySelectorAll('[data-delete]').forEach(button=>button.onclick=async()=>{
    const kind=button.dataset.delete;
    if(!confirm(kind==='topic'?'Delete this discussion and all its replies? This cannot be undone.':'Delete this reply? This cannot be undone.'))return;
    button.disabled=true;
    try{await api({},{action:kind+'Delete',id:button.dataset.id});if(kind==='topic')location.hash=newsPage?'':'list?category='+d.topic.category_id;else await load();}catch(e){$('forum-error').textContent=e.message;$('forum-error').focus();button.disabled=false;}
  });}
  function bindEdits(d){root.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>{
    const kind=button.dataset.edit,post=kind==='topic'?d.topic:d.replies.find(r=>String(r.id)===button.dataset.id);
    if(!post)return;
    const panel=button.closest('.forum-post').querySelector('.forum-post-main');if(panel.querySelector('.forum-edit-form'))return;
    const body=panel.querySelector('.forum-rich');body.hidden=true;button.hidden=true;
    const form=document.createElement('form');form.className='issue-form forum-edit-form';
    form.innerHTML=`${kind==='topic'?`<label class="forum-title-field">Title<input name="title" minlength="5" maxlength="160" required value="${esc(post.title)}"></label>`:''}<label>Message<textarea name="body" minlength="2" maxlength="10000" rows="8" required>${esc(post.body)}</textarea></label>${kind==='topic'&&d.isAdmin&&post.category_id===4?releaseField(post.github_release_url):''}${!d.isAdmin?'<p class="issue-note">You can edit this post for 24 hours after it was posted.</p>':''}${status}<div class="issue-form-actions"><button type="button" data-cancel-edit>Cancel</button><button class="issue-primary">Save changes</button></div>`;
    body.after(form);editors();form.querySelector('[name=body]').focus();
    form.querySelector('[data-cancel-edit]').onclick=()=>{form.remove();body.hidden=false;button.hidden=false;button.focus();};
    bindPost(form,f=>({...f,action:kind+'Edit',id:post.id}),async()=>{
      Object.assign(post,Object.fromEntries(new FormData(form)));
      if(kind==='topic'&&d.isAdmin&&post.category_id===4){post.github_release_url=post.releaseUrl;panel.querySelector('[data-release-link]').innerHTML=releaseLink(post);}
      body.innerHTML=rich(post.body);body.hidden=false;form.remove();button.hidden=false;
      if(kind==='topic'){root.querySelector('.forum-topic-name').textContent=post.title;document.title=post.title+(newsPage?' | News':' | Forums');}
      const saved=document.createElement('p');saved.className='issue-note';saved.setAttribute('role','status');saved.textContent='Changes saved.';panel.querySelector('[data-edit-saved]')?.remove();saved.dataset.editSaved='1';body.after(saved);button.focus();
    });
  });}
  function categoriesView(d){
    root.innerHTML=`<div class="forum-toolbar"><div class="forum-links">${d.myMemberId?'<a href="/account#community-profile">Account</a>':''}<a href="#list">All topics</a><a href="/issues">Report an issue</a>${d.isAdmin?'<a href="/admin-forum">Manage forum</a>':''}</div><button id="new-topic" class="issue-primary" ${canWrite(d)?'':'disabled'}>New discussion</button></div>${note(d)?`<p class="issue-note">${note(d)}</p>`:''}<form id="forum-search" class="issue-filters"><label class="issue-search">Search discussions<input name="q" type="search" maxlength="100" placeholder="Search titles"></label><button>Search</button></form><section id="forum-list" class="issue-results"><div class="forum-section-title"><h2>Community categories</h2></div>${d.categories.map(c=>`<article class="forum-category"><div class="forum-category-icon" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8z"/></svg></div><div class="forum-category-main"><h3><a href="#list?category=${c.id}">${esc(c.name)}</a>${c.archived?' <span class="issue-badge">Archived</span>':''}</h3><p>${esc(c.description)}</p>${c.latest_id?`<div class="forum-latest"><a href="#topic/${c.latest_id}">${esc(c.latest_title)}</a><span>${date(c.latest_at)}</span></div>`:'<span class="issue-note">No discussions yet</span>'}</div><div class="forum-category-count"><strong>${c.topic_count+c.reply_count}</strong><span>posts</span><small>${c.topic_count} topics</small></div></article>`).join('')}</section>`;
    $('new-topic').onclick=()=>newTopic(d);$('forum-search').onsubmit=e=>{e.preventDefault();location.hash='list?'+new URLSearchParams(new FormData(e.currentTarget));};
  }
  const options=(cats,value,filter=false,admin=false)=>cats.filter(c=>!filter||(!c.archived&&(c.id!==4&&!c.read_only||admin))).map(c=>`<option value="${c.id}" ${Number(value)===c.id?'selected':''}>${esc(c.name)}${c.archived?' (archived)':''}</option>`).join('');
  const pager=(data,link)=>`<nav class="issue-pagination" aria-label="Discussion pages">${data.page>1?`<a href="${link(data.page-1)}">← Previous</a>`:''}<span>Page ${data.page}</span>${data.hasMore?`<a href="${link(data.page+1)}">Next →</a>`:''}</nav>`;
  const status='<p data-status class="issue-error" role="alert" tabindex="-1"></p>';
  const canWrite=d=>d.canPost&&(d.postingOpen||d.isAdmin);
  const note=d=>!d.authenticated?`<a href="/account?next=${encodeURIComponent(pagePath+location.hash)}">Sign in with Nuvio</a> to join the conversation.`:!d.canPost?'Posting is disabled for your account.':!d.postingOpen?'The forum is temporarily read-only.':'';
  function bindPost(form,data,success){form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;submit(form,async()=>{const result=await api({},data(Object.fromEntries(new FormData(form))));await success(result);});});}
  function newTopic(d){
    if($('new-topic-form'))return;
    const categoryId=newsPage?d.announcementsCategoryId:d.selectedCategory;
    if(!categoryId){
      if($('choose-topic-category'))return;
      const chooser=document.createElement('section');chooser.id='choose-topic-category';chooser.className='issue-card';chooser.innerHTML='<h2>Choose a category</h2><div class="forum-category-choices">'+d.categories.filter(c=>!c.archived&&(!c.read_only||d.isAdmin)).map(c=>`<a href="#list?category=${c.id}&new=1">${esc(c.name)}</a>`).join('')+'</div>';$('forum-list').before(chooser);return;
    }

    const section=document.createElement('section');section.className='issue-card';section.innerHTML=`<form id="new-topic-form" class="issue-form"><h2>${newsPage?'Publish news':'New discussion'}</h2><input type="hidden" name="categoryId" value="${categoryId}"><label class="forum-title-field">Title<input name="title" minlength="5" maxlength="160" required placeholder="What would you like to discuss?"></label><label>Message<textarea name="body" minlength="2" maxlength="10000" rows="6" required></textarea></label>${d.isAdmin&&Number(categoryId)===4?releaseField():''}<p class="issue-note">${Number(categoryId)===4?'Publishing adds this post to News, Announcements, and the homepage. Comments are shared across both pages.':'Posts are public; keep passwords and API keys private.'}</p>${status}<div class="issue-form-actions"><button type="button" id="cancel-topic">Cancel</button><button class="issue-primary">${newsPage?'Publish news':'Post discussion'}</button></div></form>`;
    $('forum-list').before(section);$('cancel-topic').onclick=()=>section.remove();editors();section.querySelector('[name=title]').focus();
    bindPost($('new-topic-form'),f=>({...f,action:newsPage?'news':'topic'}),r=>{location.hash='topic/'+r.id;});
  }
  function listView(d,params){
    const category=d.categories.find(c=>c.id===Number(params.get('category')));d.selectedCategory=category?.id;
    const link=p=>(d.followingView?'#followed?':'#list?')+new URLSearchParams({...Object.fromEntries(params),page:p});
    root.innerHTML=`${back()}<header class="issue-card forum-category-header"><h2>${esc(d.followingView?'Followed topics':category?.name||'All topics')}</h2><p>${esc(d.followingView?'Topics you follow. New replies are marked below.':category?.description||'The latest conversations from every category.')}</p>${category?.id===4?'<p class="issue-note">Only the site owner can publish announcements. Members can comment on existing posts. Announcements also appear on News and the homepage.</p>':''}</header><div class="forum-toolbar"><div class="forum-links">${d.myMemberId?'<a href="/account#community-profile">Account</a>':''}<a href="/issues">Report an issue</a>${d.isAdmin?'<a href="/admin-forum">Manage forum</a>':''}</div><button id="new-topic" class="issue-primary" ${canWrite(d)&&(!category||!category.archived&&(!category.read_only||d.isAdmin))?'':'disabled'}>New discussion</button></div>${note(d)?`<p class="issue-note">${note(d)}</p>`:''}<form id="forum-filter" class="issue-filters"><label class="issue-search">Search discussions<input name="q" type="search" maxlength="100" value="${esc(params.get('q'))}" placeholder="Search titles"></label><label>Category<select name="category"><option value="">All categories</option>${options(d.categories,params.get('category'))}</select></label><button>Search</button></form><div id="forum-list" class="issue-results">${rows(d.topics)}</div>${pager(d,link)}`;
    $('forum-filter').onsubmit=e=>{e.preventDefault();location.hash='list?'+new URLSearchParams(new FormData(e.currentTarget));};$('new-topic').onclick=()=>newTopic(d);if(params.get('new')==='1')newTopic(d);
  }
  const replyHtml=(r,d)=>postHtml(r,d,'reply');
  function bindModeration(){root.querySelectorAll('[data-reply]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api({},{action:'replyModerate',id:b.dataset.reply,hidden:b.dataset.hidden==='1'});await load();}catch(e){$('forum-error').textContent=e.message;b.disabled=false;}});}
  function topicView(d){
    const t=d.topic;document.title=t.title+(newsPage?' | News':' | Forums');
    root.innerHTML=`<nav class="forum-breadcrumbs" aria-label="Discussion navigation">${back()}<span aria-hidden="true">/</span><a href="${newsPage?'/discussions#topic/'+t.id:'#list?category='+t.category_id}">${newsPage?'View in Announcements':esc(t.category_name)}</a>${!newsPage&&t.category_id===4?`<a href="/news.html#topic/${t.id}">View in News</a>`:''}</nav><header class="forum-topic-heading"><div class="forum-topic-title"><h2 class="forum-topic-name">${esc(t.title)}</h2><div class="issue-meta">${flags(t)}</div></div><div class="forum-topic-details"><div class="forum-topic-byline">${window.KollectionIssueMedia.avatar(t.author,t.avatar_url,t.avatar_color)}<div class="forum-topic-author-info"><span class="forum-topic-author-line">By <a href="/discussions#member/${encodeURIComponent(t.member_id)}">${esc(t.author)}</a></span><span class="forum-topic-date"><time datetime="${esc(t.created_at)}">${date(t.created_at)}</time> in <a href="/discussions#list?category=${t.category_id}">${esc(t.category_name)}</a></span></div></div><div class="forum-topic-shortcuts"><button type="button" data-share="topic" data-id="${t.id}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/></svg><span>Share</span></button><button type="button" id="follow-topic" aria-pressed="${!!t.following}" ${!d.canPost||t.hidden?'disabled':''} title="${d.authenticated?'See new replies in your followed topics':'Sign in to follow this topic'}"><span data-follow-label>${t.following?'Following':'Follow'}</span><span class="forum-follow-count">${t.follower_count||0}</span></button></div></div></header><div class="forum-topic-reply-row">${canWrite(d)&&(!t.locked||d.isAdmin)&&!t.hidden?'<a class="forum-reply-shortcut" href="#" id="jump-to-reply">Reply to topic</a>':''}</div>${postHtml(t,d,'topic')}<h2>${newsPage?'Comments':'Replies'} <span class="issue-badge">${t.reply_count}</span></h2><div id="forum-replies">${d.replies.map(r=>replyHtml(r,d)).join('')||(newsPage?'<p>No comments yet.</p>':'<p>No replies yet.</p>')}</div><button id="more-replies" ${d.hasMore?'':'hidden'}>${newsPage?'Load more comments':'Load more replies'}</button>${canWrite(d)&&(!t.locked||d.isAdmin)&&!t.hidden?`<form id="reply-form" class="issue-card issue-form"><label>${newsPage?'Add a comment':'Add a reply'}<textarea name="body" minlength="2" maxlength="10000" rows="4" required></textarea></label>${status}<div class="issue-form-actions"><button class="issue-primary">${newsPage?'Post comment':'Post reply'}</button></div></form>`:`<p class="issue-note">${t.hidden?'This discussion is hidden.':t.locked?'This discussion is locked.':note(d)}</p>`}`;
    $('follow-topic').onclick=async()=>{const b=$('follow-topic');b.disabled=true;try{const r=await api({},{action:'follow',id:t.id,following:!t.following});Object.assign(t,r);b.setAttribute('aria-pressed',String(r.following));b.querySelector('[data-follow-label]').textContent=r.following?'Following':'Follow';b.querySelector('.forum-follow-count').textContent=r.follower_count;}catch(e){$('forum-error').textContent=e.message;}finally{b.disabled=false;}};
    if($('manage-topic-toggle'))$('manage-topic-toggle').onclick=()=>{const panel=$('topic-management');panel.hidden=!panel.hidden;$('manage-topic-toggle').setAttribute('aria-expanded',String(!panel.hidden));};
    if($('jump-to-reply'))$('jump-to-reply').onclick=e=>{e.preventDefault();$('reply-form').scrollIntoView({block:'center',behavior:'smooth'});$('reply-form').querySelector('textarea').focus();};
    bindPost($('moderate-topic'),f=>({action:'topicModerate',id:t.id,categoryId:f.categoryId,pinned:f.pinned==='on',locked:f.locked==='on',hidden:f.hidden==='on'}),load);
    bindPost($('reply-form'),f=>({...f,action:'reply',id:t.id}),async()=>{await load();const message=document.createElement('p');message.className='issue-note';message.setAttribute('role','status');message.textContent=newsPage?'Your comment was posted.':'Your reply was posted.';$('reply-form')?.before(message);});
    let after=d.replies.at(-1)?.id||0;const route=version;
    $('more-replies').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{const more=await api({view:newsPage?'newsTopic':'topic',id:t.id,after});if(route!==version)return;d.replies.push(...more.replies);$('forum-replies').insertAdjacentHTML('beforeend',more.replies.map(r=>replyHtml(r,d)).join(''));after=more.replies.at(-1)?.id||after;b.hidden=!more.hasMore;bindModeration();bindDeletes(d);bindEdits(d);bindSocial(d);}catch(e){$('forum-error').textContent=e.message;}finally{b.disabled=false;}};bindModeration();bindDeletes(d);bindEdits(d);bindSocial(d);editors();const target=new URLSearchParams(location.hash.split('?')[1]||'').get('reply');if(target)$('reply-'+target)?.scrollIntoView({block:'center'});
  }
  function memberView(d,params){const m=d.member;document.title=m.author+' | The Kollection';root.innerHTML=`<div class="forum-toolbar">${back()}${d.myMemberId===m.member_id?'<a href="/account#community-profile">Edit profile</a>':''}</div><article class="issue-card"><div class="forum-profile-head">${window.KollectionIssueMedia.avatar(m.author,m.avatar_url,m.avatar_color)}<div><h2>${esc(m.author)}</h2><p class="issue-note">Joined ${date(m.created_at)}</p></div></div><dl class="forum-stats"><div><dt>Posts</dt><dd>${m.topic_count+m.reply_count}</dd></div><div><dt>Topics</dt><dd>${m.topic_count}</dd></div><div><dt>Replies</dt><dd>${m.reply_count}</dd></div><div><dt>Likes received</dt><dd>${m.likes_received||0}</dd></div></dl><h2>About me</h2><p class="issue-body">${esc(m.about||'Nothing shared yet.')}</p></article><h2>Topics started</h2><div class="issue-results">${rows(d.topics)}</div>${pager(d,p=>'#member/'+m.member_id+'?page='+p)}`;}

  function newsView(d,params){
    root.innerHTML=`<div id="forum-list">${d.articles.map(t=>{
      const readable=window.KollectionForumEditor?.plainMentions?.(t.body)??t.body;
      const plain=readable.replace(/\[([^\]]+)\]\(https?:[^)]+\)/g,'$1').replace(/[*+`>#]/g,'');
      return `<article class="release news-article" id="news-${t.id}"><div class="news-entry-content"><div class="release-tag">The Kollection</div><h2><a href="#topic/${t.id}">${esc(t.title)}</a></h2><div class="release-meta">${date(t.created_at)} · ${esc(t.author)}</div><p class="release-summary" data-summary>${esc(plain.slice(0,320))}${plain.length>320?'…':''}</p><div class="forum-rich news-full" id="news-body-${t.id}" hidden>${rich(t.body)}</div></div><div class="release-actions"><button type="button" data-expand aria-expanded="false" aria-controls="news-body-${t.id}">Show more</button>${releaseLink(t)}<a class="news-comment-link" href="#topic/${t.id}" aria-label="${t.reply_count} ${t.reply_count===1?'comment':'comments'} on ${esc(t.title)}" title="View comments"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8z"/></svg><span aria-hidden="true">${t.reply_count}</span></a></div></article>`;
    }).join('')||'<p>No news posts yet.</p>'}</div>${pager(d,p=>'#news?page='+p)}`;
    if($('post-news')){$('post-news').hidden=!d.isAdmin;$('post-news').onclick=()=>newTopic(d);}
    root.querySelectorAll('[data-expand]').forEach(button=>button.onclick=()=>{const article=button.closest('article'),full=article.querySelector('.news-full'),show=full.hidden;full.hidden=!show;article.querySelector('[data-summary]').hidden=show;button.textContent=show?'Show less':'Show more';button.setAttribute('aria-expanded',String(show));});
  }
  async function load(){if($('post-news'))$('post-news').hidden=true;const current=++version;$('forum-error').textContent='';root.setAttribute('aria-busy','true');const [route,query='']=location.hash.slice(1).split('?'),params=new URLSearchParams(query),[view,key]=route.split('/');
    forumPage?.classList.toggle('forum-topic-page',view==='topic');
    try{const data=await api({...Object.fromEntries(params),view:newsPage?(view==='topic'?'newsTopic':view==='kollection-250'?'newsLegacy':'news'):(view==='topic'||view==='member'||view==='followed'?view:!view?'categories':'list'),...(key?{id:key}:{})});if(current!==version)return;document.title=(newsPage?'News':'Forums')+' | The Kollection';if(newsPage){if(view==='topic'||view==='kollection-250')topicView(data);else newsView(data,params);}else if(view==='topic')topicView(data);else if(view==='member')memberView(data,params);else if(!view)categoriesView(data);else listView(data,params);}catch(e){if(current!==version)return;root.innerHTML=back()+'<p><button id="retry-forum">Try again</button></p>';$('forum-error').textContent=e.message;$('retry-forum').onclick=load;}finally{if(current===version)root.removeAttribute('aria-busy');}}
  window.addEventListener('hashchange',()=>{load();});window.addEventListener('kollection:nuvio-signed-out',load);window.addEventListener('kollection:nuvio-signed-in',load);load();
})();
